title: "chk03042010"
description: "Learning and Exploiting Binaries"
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

author:
  name: "chk03042010"

